/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post117, git sha1 b5170e139) */

(* top =  1  *)
(* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:168" *)
(* generator = "Amaranth" *)
module alu_7_segment(SWT, clk, rst, SEG, AN, CLK);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire \$1 ;
  wire [2:0] \$2 ;
  wire [17:0] \$3 ;
  reg [16:0] \$4 ;
  reg [1:0] \$5 ;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:165" *)
  output [3:0] AN;
  reg [3:0] AN;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:160" *)
  input CLK;
  wire CLK;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:21" *)
  output [6:0] SEG;
  wire [6:0] SEG;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:161" *)
  input [15:0] SWT;
  wire [15:0] SWT;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:171" *)
  wire [3:0] a;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:80" *)
  wire [3:0] \a$9 ;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:172" *)
  wire [3:0] b;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:81" *)
  wire [3:0] \b$10 ;
  (* src = "/home/stephan/Git/bloggg/venv/lib/python3.12/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:173" *)
  wire [3:0] control;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:82" *)
  wire [3:0] \control$11 ;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:210" *)
  reg [3:0] current_digit;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:19" *)
  wire [3:0] digit;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:195" *)
  wire [3:0] digit_0;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:196" *)
  wire [3:0] digit_1;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:197" *)
  wire [3:0] digit_2;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:198" *)
  wire [3:0] digit_3;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:209" *)
  reg [1:0] digit_select = 2'h0;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:208" *)
  reg [16:0] refresh_counter = 17'h00000;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:174" *)
  wire [7:0] result;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:85" *)
  wire [7:0] \result$13 ;
  (* src = "/home/stephan/Git/bloggg/venv/lib/python3.12/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:21" *)
  wire [6:0] segments;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:208" *)
  always @(posedge clk)
    refresh_counter <= \$4 ;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:209" *)
  always @(posedge clk)
    digit_select <= \$5 ;
  assign \$1  = refresh_counter == (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:213" *) 17'h1869f;
  assign \$2  = digit_select + (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:216" *) 1'h1;
  assign \$3  = refresh_counter + (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:219" *) 1'h1;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:185" *)
  \alu_7_segment.alu  alu (
    .control(SWT[15:12]),
    .\port$0$3 (SWT[7:0]),
    .result(result)
  );
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:251" *)
  \alu_7_segment.decoder  decoder (
    .digit(current_digit),
    .segments(SEG)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (digit_select)
      2'h0:
          current_digit = SWT[3:0];
      2'h1:
          current_digit = SWT[7:4];
      2'h2:
          current_digit = result[3:0];
      2'h3:
          current_digit = result[7:4];
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$4  = 17'h00000;
    end else begin
      \$4  = \$3 [16:0];
    end
    if (rst) begin
      \$4  = 17'h00000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$5  = digit_select;
    if (\$1 ) begin
      \$5  = \$2 [1:0];
    end
    if (rst) begin
      \$5  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (digit_select)
      2'h0:
          AN = 4'he;
      2'h1:
          AN = 4'hd;
      2'h2:
          AN = 4'hb;
      2'h3:
          AN = 4'h7;
    endcase
  end
  assign a = SWT[7:4];
  assign b = SWT[3:0];
  assign control = SWT[15:12];
  assign \a$9  = SWT[7:4];
  assign \b$10  = SWT[3:0];
  assign \control$11  = SWT[15:12];
  assign \result$13  = result;
  assign digit_0 = SWT[3:0];
  assign digit_1 = SWT[7:4];
  assign digit_2 = result[3:0];
  assign digit_3 = result[7:4];
  assign digit = current_digit;
  assign segments = SEG;
endmodule

(* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:88" *)
(* generator = "Amaranth" *)
module \alu_7_segment.alu (control, result, \port$0$3 );
  reg \$auto$verilog_backend.cc:2355:dump_module$2  = 0;
  wire [8:0] \$1 ;
  wire [7:0] \$12 ;
  wire \$14 ;
  wire [8:0] \$2 ;
  wire [7:0] \$3 ;
  wire \$4 ;
  wire [7:0] \$5 ;
  wire [7:0] \$6 ;
  wire [7:0] \$7 ;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:80" *)
  wire [3:0] a;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:91" *)
  wire [7:0] a_extended;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:81" *)
  wire [3:0] b;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:92" *)
  wire [7:0] b_extended;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:82" *)
  input [3:0] control;
  wire [3:0] control;
  input [7:0] \port$0$3 ;
  wire [7:0] \port$0$3 ;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:85" *)
  output [7:0] result;
  reg [7:0] result;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:107" *)
  reg [8:0] subtraction;
  assign \$3  = \port$0$3 [7:4] * (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:118" *) \port$0$3 [3:0];
  assign \$4  = ! (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:122" *) \port$0$3 [3:0];
  assign \$12  = \port$0$3 [7:4] / (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:126" *) \port$0$3 [3:0];
  assign \$14  = | (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:126" *) \port$0$3 [3:0];
  assign \$5  = \$14  ? (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:126" *) \$12  : 8'h00;
  assign \$6  = { 4'h0, \port$0$3 [7:4] } & (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:130" *) { 4'h0, \port$0$3 [3:0] };
  assign \$7  = { 4'h0, \port$0$3 [7:4] } | (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:134" *) { 4'h0, \port$0$3 [3:0] };
  assign \$1  = \port$0$3 [7:4] + (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:103" *) \port$0$3 [3:0];
  assign \$2  = \port$0$3 [7:4] - (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:108" *) \port$0$3 [3:0];
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    casez (control)
      4'h0:
          result = \$1 [7:0];
      4'h1:
          (* full_case = 32'd1 *)
          if (subtraction[8]) begin
            result = 8'h00;
          end else begin
            result = subtraction[7:0];
          end
      4'h2:
          result = \$3 ;
      4'h3:
          (* full_case = 32'd1 *)
          if (\$4 ) begin
            result = 8'hff;
          end else begin
            result = \$5 ;
          end
      4'h4:
          result = \$6 ;
      4'h5:
          result = \$7 ;
      default:
          result = 8'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$2 ) begin end
    subtraction = 9'h000;
    casez (control)
      4'h0:
          /* empty */;
      4'h1:
          subtraction = \$2 ;
    endcase
  end
  assign a_extended = { 4'h0, \port$0$3 [7:4] };
  assign a = \port$0$3 [7:4];
  assign b_extended = { 4'h0, \port$0$3 [3:0] };
  assign b = \port$0$3 [3:0];
endmodule

(* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:24" *)
(* generator = "Amaranth" *)
module \alu_7_segment.decoder (segments, digit);
  reg \$auto$verilog_backend.cc:2355:dump_module$3  = 0;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:19" *)
  input [3:0] digit;
  wire [3:0] digit;
  (* src = "/home/stephan/Git/bloggg/doc/Uni/20251112/alu_7_segment.py:21" *)
  output [6:0] segments;
  reg [6:0] segments;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$3 ) begin end
    (* full_case = 32'd1 *)
    casez (digit)
      4'h0:
          segments = 7'h40;
      4'h1:
          segments = 7'h79;
      4'h2:
          segments = 7'h24;
      4'h3:
          segments = 7'h30;
      4'h4:
          segments = 7'h19;
      4'h5:
          segments = 7'h12;
      4'h6:
          segments = 7'h02;
      4'h7:
          segments = 7'h78;
      4'h8:
          segments = 7'h00;
      4'h9:
          segments = 7'h10;
      4'ha:
          segments = 7'h08;
      4'hb:
          segments = 7'h03;
      4'hc:
          segments = 7'h46;
      4'hd:
          segments = 7'h21;
      4'he:
          segments = 7'h06;
      4'hf:
          segments = 7'h0e;
    endcase
  end
endmodule
