## Clock signal (100MHz) - Not used in this design but included for reference
#set_property PACKAGE_PIN W5 [get_ports CLK]
#    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
#    create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]

## Switches
set_property PACKAGE_PIN V17 [get_ports {SWT[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[0]}]
set_property PACKAGE_PIN V16 [get_ports {SWT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[1]}]
set_property PACKAGE_PIN W16 [get_ports {SWT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[2]}]
set_property PACKAGE_PIN W17 [get_ports {SWT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[3]}]
set_property PACKAGE_PIN W15 [get_ports {SWT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[4]}]
set_property PACKAGE_PIN V15 [get_ports {SWT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[5]}]
set_property PACKAGE_PIN W14 [get_ports {SWT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[6]}]
set_property PACKAGE_PIN W13 [get_ports {SWT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[7]}]
set_property PACKAGE_PIN V2 [get_ports {SWT[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[8]}]
set_property PACKAGE_PIN T3 [get_ports {SWT[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[9]}]
set_property PACKAGE_PIN T2 [get_ports {SWT[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[10]}]
set_property PACKAGE_PIN R3 [get_ports {SWT[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[11]}]
set_property PACKAGE_PIN W2 [get_ports {SWT[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[12]}]
set_property PACKAGE_PIN U1 [get_ports {SWT[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[13]}]
set_property PACKAGE_PIN T1 [get_ports {SWT[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[14]}]
set_property PACKAGE_PIN R2 [get_ports {SWT[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SWT[15]}]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]

## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]